---
# Tool for automatic porting of PS5 executables to Linux and Windows

- name: Install dependencies
  community.general.pacman:
    name:
      - base-devel
      - cmake
      - git
      - ninja
    state: latest
  become: true

- name: Set build facts
  ansible.builtin.set_fact:
    anyps5_dirs:
      root: "{{ user_project_dir }}/repos/AnyPS5"
      build: "{{ user_project_dir }}/repos/AnyPS5/build"
      install: "{{ user_dir }}/.local/bin"

- name: Get latest release
  ansible.builtin.uri:
    url: "https://api.github.com/repos/boykopovar/AnyPS5/releases/latest"
    headers:
      Content-Type: application/json
  register: anyps5_latest_release

- name: Set version fact
  ansible.builtin.set_fact:
    anyps5_latest: "{{ anyps5_latest_release.json.tag_name }}"

- name: Clone repo
  ansible.builtin.git:
    repo: "https://github.com/boykopovar/AnyPS5"
    dest: "{{ anyps5_dirs.root }}"
    depth: 1
    recursive: false
    version: "{{ anyps5_latest }}"

- name: Initialize submodules (shallow, parallel) # noqa: command-instead-of-module
  ansible.builtin.command:
    cmd: "git submodule update --init --recursive --recommend-shallow --depth 1 --jobs {{ nproc // 2 }}"
    chdir: "{{ anyps5_dirs.root }}"
  register: anyps5_submod_init
  changed_when: false

- name: Check for build directory
  ansible.builtin.stat:
    path: "{{ anyps5_dirs.build }}"
  register: anyps5_build_dir

- name: Clean build artifacts
  ansible.builtin.file:
    path: "{{ anyps5_dirs.build }}"
    state: absent
  when: anyps5_build_dir.stat.exists

- name: Build
  block:
    - name: CMake - Generate Ninja build files
      ansible.builtin.command:
        chdir: "{{ anyps5_dirs.root }}"
        cmd: "cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release"
      changed_when: false

    - name: CMake - Build
      ansible.builtin.command:
        chdir: "{{ anyps5_dirs.build }}"
        cmd: "cmake --build ."
      changed_when: false

- name: Install relinker to {{ anyps5_dirs.install }}
  ansible.builtin.copy:
    src: "{{ anyps5_dirs.build }}/core/relinker/relinker"
    dest: "{{ anyps5_dirs.install }}/relinker"
    mode: "0755"
